### ISSUE TITLE
Codepoint 42 not allowed

### ISSUE THREAD

**Issue by niccolox** [seomoz/publicsuffix-elixir#35]
I am trying to get this running, using this repo and also a fork https://github.com/axelson/publicsuffix-elixir and I am getting the error below. 

I am stumped, presumably a dependency issue?

```
PublicSuffix: fetched fresh data file for compilation.

== Compilation error in file lib/public_suffix.ex ==
** (exit) {:bad_label, {:alabel, 'The label "*"  is not a valid A-label: ulabel error={bad_label,\n                                                     {context,\n                                                      "Codepoint 42 not allowed (\'DISALLOWED\') at position 0 in \\"*\\""}}'}}
    //deps/idna/src/idna.erl:281: :idna.alabel/1
    //deps/idna/src/idna.erl:149: :idna.encode_1/2
    lib/public_suffix/rules_parser.ex:62: PublicSuffix.RulesParser.punycode_domain/1
    lib/public_suffix/rules_parser.ex:35: anonymous fn/1 in PublicSuffix.RulesParser.parse_rules_section/2
    (elixir 1.10.2) lib/stream.ex:466: anonymous fn/3 in Stream.flat_map/2
    (elixir 1.10.2) lib/stream.ex:902: Stream.do_transform_user/6
    (elixir 1.10.2) lib/enum.ex:3383: Enum.split_with/2
    lib/public_suffix/rules_parser.ex:38: PublicSuffix.RulesParser.parse_rules_section/2
could not compile dependency :public_suffix, "mix compile" failed. You can recompile this dependency with "mix deps.compile public_suffix", update it with "mix deps.update public_suffix" or clean it with "mix deps.clean public_suffix"
```

**Comment by niccolox** [comment]
resolved with mix deps.update --all
damn I love the Elixir / Erlang ecosystem
